# Generated by Django 2.2.16 on 2022-09-28 10:36

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220927_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color_hex',
            field=models.CharField(max_length=7, validators=[recipes.validators.hex_color_valid], verbose_name='Tag color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Name cooking tag', max_length=200, unique=True, verbose_name='Cooking tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Cooking slug', unique=True),
        ),
    ]
