# Generated by Django 2.2.16 on 2022-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220930_1103'),
        ('users', '0002_auto_20220928_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow',
            new_name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='is_favorite',
            field=models.ManyToManyField(related_name='is_favorite', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(related_name='is_in_shopping_cart', to='recipes.Recipe'),
        ),
    ]
