# Generated by Django 2.2.16 on 2022-10-03 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220930_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='is_favorite', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='is_in_shopping_cart', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
