# Generated by Django 2.2.16 on 2022-10-05 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221003_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
